### PR TITLE
Calculate some times and display them in big number

### PR DESCRIPTION
**Pull request by danwang**

### CODE REVIEW

**Comment by erictzeng** [comment]
You need to implement `RegistrarsController#index` too. They're rendering the same template, just that you should be calculating the value across all Registrars instead of a particular one.

**Comment by erictzeng** [comment]
Also, write specs!

**Comment by danwang** [comment]
I'm kind of wary of having the same view for index and show. It doesn't make sense to have an @registrar variable available in the view, because index doesn't use it. I'm afraid that the controller will have to assign a bunch of variables that could have been done in the view. Thoughts?

**Comment by erictzeng** [comment]
After a fairly heated debate that neither of us are really satisfied with, we've decided to stick with the way it is now.

@danwang write specs/greenify cucumber tests thanks

**Pull request merged**
