### PR TITLE
Scenario for overriding drug usage rates

### PR DESCRIPTION
**Pull request by danwang**
Not sure about DRYing out

`When I change the usage rate for "drug A" to 20 per day`

and 

`Given I have changed the usage rate for "drug A" to 20 per day`

### CODE REVIEW

**Comment by erictzeng** [comment]
We're not going to have users, so you can leave out the line about logging in.

As for DRYing things out, why not just have the regex match both? Shouldn't be that bad:

``` ruby
/^I( have)? changed? the usage rate for "(.*)" to (.*)$/
```

Or something like that, at least.

**Comment by erictzeng** [comment]
Also, more tests for sad paths. What happens if someone enters an invalid amount? Things like that.

**Comment by danwang** [comment]
How much of input validation should be tested with cucumber?

Writing something like

`When I change the usage rates for "drug A" to 20 per day`

is nice because the `20` is given as a number, so the units are implied. In the case that someone inputs a non-number, how should you check this?

Something for the future: How should we handle different types of units? I can imagine something that is used very sparingly, and instead of something like `0.0027 per day`, we can write `1 per year`. The same goes for `low_stock_alert`.

**Comment by seshness** [comment]
lgtm

**Pull request merged**
