### PR TITLE
Pharmacy low stock alerts

### PR DESCRIPTION
**Pull request by bucephalus**
This isn't actually complete yet.  The following, at least, needs to be fixed:

1) Procedure to set low_stock_point in cucumber feature
I don't know what it is you click on to get to the edit form

2) Representation of alert in cucumber feature
I don't know how we're representing the line between drugs with alert and those without

3) Anything that follows after working out 1 and 2

### CODE REVIEW

**Comment by erictzeng** [comment]
1. If you're using capybara, then you don't need to click anything. Javascript hides the form on page load, but capybara doesn't support javascript.
2. Can you add a class like `alert` to the appropriate `tr`? Then add a CSS style to make it a pink color instead of the off-white that it is now.

**Comment by bucephalus** [comment]
Sorry, I don't know what you're talking about in 2.  Could you explain?

**Comment by bucephalus** [comment]
By the way, is there a way that I can copy the view files into my branch?

**Comment by erictzeng** [comment]
Do you know HTML/CSS? The `tr` tags with class `info` are the ones that display by default on the view. The best way to highlight alerts is probably add the `alert` class to the `tr` (or you could even replace it completely). Then add a rule in the css file so that anything with the `alert` class gets displayed with a pink background color.

As for how to get the view files:
1. Checkout `master`
2. Pull
3. Checkout your feature branch
4. `git merge master`

**Comment by bucephalus** [comment]
Ah.  No, I'm not too familiar with HTML/CSS.  I can try to do that, though.

Thanks

**Comment by erictzeng** [comment]
Sounds good. Let us know if you need any help.

**Pull request merged**
