### PR TITLE
Pharmacy low stock alerts cucumber tests

### PR DESCRIPTION
**Pull request by bucephalus**
added cucumber tests and step definitions.

new files:
features/pharmacy_low_stock_alerts.feature
features/step_definitions/drug_steps.rb

tests currently fail because there is no Drug model.

Assumed Drug model has fields:
id
name
quantity
units
calculated_usage_rate
static_usage_rate
low_stock_point
low_stock_alert

### CODE REVIEW

**Comment by bucephalus** [comment]
Question: Do I need to do anything to this pull request before I perform the changes to the files involved?  Or can I just commit and push as normal?

Responses to above:

I will remove underscores from statements in feature file

How can I pull the changes to drug_steps.rb from the sparklines-feature branch?

Manually setting the low stock point of a drug and automatically setting the low stock point of a drug result in the same expectations, but are done differently.  The step definition for manually setting goes through the actions taken on the edit page.  The step definition for auto-setting is currently just an assignment, but may change based upon methods we implement for getting the calculated low stock point.  I wanted to keep them separate because there are two ways to set the low stock point, which I believed should be tested separately.

I can use on/off instead.  Thanks for the suggestion.

**Comment by seshness** [comment]
make the changes to the files in a separate commit on the same branch, ie. pharmacy_low_stock_alerts_cucumber_tests.

Then, push that branch as you did before. The changed you made will show up here.

On manual/automatic: let automatic be written as it's meant to be written. We don't need to implement the step definitions for this iteration just yet.

**Comment by seshness** [comment]
Sorry, that was me hitting the wrong button.

**Comment by bucephalus** [comment]
Thanks guys!

Eric: I caught those when I was writing the step definitions.  Forgot to mention it in the commit log.  Sorry!

**Comment by seshness** [comment]
lgtm

**Pull request merged**
